apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-redis-add-task-cron
  labels:
    cronjob: app-redis-add-task-cron
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        job: app-redis-add-task-cron
    spec:
      # job level
      backoffLimit: 2
      template:
        spec:
          # pod level
          restartPolicy: Never # Never, OnFailure
          containers:
            - name: app-redis-add-task-container
              image: 'redis:8.6.1'
              command:
                - 'redis-cli'
                - '-h'
                - 'app-redis-v1-0.app-redis-service.default'
                - 'RPUSH'
                - 'queue'
                - 'task3'
              resources:
                requests:
                  cpu: '100m'
                  memory: '10Mi'