apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-daemon-set
spec:
  selector:
    matchLabels:
      ds: app-pod-label-v18
  # Pod
  template:
    metadata:
      labels:
        ds: app-pod-label-v18
    spec:
      terminationGracePeriodSeconds: 2
      volumes:
        - name: sys-log-volume
          hostPath:
            path: /var/log/
      containers:
        - name: sys-log-container
          image: 'grinway/k8s_test:v18'
          securityContext:
#            runAsNonRoot: true
#            runAsUser: 100
#            runAsGroup: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
              ephemeral-storage: 100Mi
          command:
            - sh
            - '-c'
            - |
              tail -f /var/log/*.log
              tail -f /var/log/**/*.log
              tail -f /var/log/**/**/*.log
          volumeMounts:
            - name: sys-log-volume
              mountPath: /var/log/
              readOnly: true