apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    hostPathProvisionerIdentity: 10321524-5f71-40dd-bd1d-08a3554f644a
    pv.kubernetes.io/provisioned-by: k8s.io/minikube-hostpath
  creationTimestamp: "2026-03-07T10:56:47Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-bf2df702-9280-4a9b-b202-1054a1a072ed
  resourceVersion: "15548"
  uid: 22c88d70-5662-44bb-af70-be6ce4c0be46
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: app-redis-pvc-app-redis-v1-0
    namespace: default
    resourceVersion: "15538"
  hostPath:
    path: /tmp/hostpath-provisioner/default/app-redis-pvc-app-redis-v1-0
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2026-03-07T10:56:47Z"
  phase: Bound